import {
  AdminIcon,
  ChatIcon,
  DocumentsIcon,
  DrafterIcon,
  JudgmentsIcon,
  KnowledgeIcon,
  ProfilIcon,
  PromptsIcon,
  TrialRoomIcon,
} from '../Layout/RealisticIcons';
import type { NavItem } from '../../types/navigation';

export const NAV_ITEMS: NavItem[] = [
  {
    id: 'chat',
    icon: ChatIcon,
    label: 'Czat',
    sublabel: 'Silnik Neuronowy',
    color: '#0284c7',
    colorRgb: '2, 132, 199',
  },
  {
    id: 'trial',
    icon: TrialRoomIcon,
    label: 'Sala rozprawy',
    sublabel: 'Symulacja procesu',
    color: '#eab308',
    colorRgb: '234, 179, 8',
  },
  {
    id: 'drafter',
    icon: DrafterIcon,
    label: 'Kreator Pism',
    sublabel: 'Generator Dokumentów',
    color: '#f97316',
    colorRgb: '249, 115, 22',
  },
  {
    id: 'judgments',
    icon: JudgmentsIcon,
    label: 'Orzecznictwo',
    sublabel: 'Precedensy Prawne',
    color: '#dc2626',
    colorRgb: '220, 38, 38',
  },
  {
    id: 'documents',
    icon: DocumentsIcon,
    label: 'Dokumentacja',
    sublabel: 'Twoje Dokumenty',
    color: '#fbbf24',
    colorRgb: '251, 191, 36',
  },
  {
    id: 'prompts',
    icon: PromptsIcon,
    label: 'Prompty',
    sublabel: 'Instrukcje AI',
    color: '#8b5cf6',
    colorRgb: '139, 92, 246',
  },
  {
    id: 'knowledge',
    icon: KnowledgeIcon,
    label: 'Baza Wiedzy',
    sublabel: 'Archiwa Prawne',
    color: '#059669',
    colorRgb: '5, 150, 105',
  },
  {
    id: 'settings',
    icon: ProfilIcon,
    label: 'Profil',
    sublabel: 'Tożsamość',
    color: '#475569',
    colorRgb: '71, 85, 105',
  },
  {
    id: 'admin',
    icon: AdminIcon,
    label: 'Admin',
    sublabel: 'Rdzeń Systemu',
    color: '#1d4ed8',
    colorRgb: '29, 78, 216',
    adminOnly: true,
  },
];
