import os
import httpx
import asyncio
from dotenv import load_dotenv

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL", "https://dhyvxspgsktpbjonejek.supabase.co")
SUPABASE_ANON_KEY = os.getenv("SUPABASE_ANON_KEY", "sb_publishable_8HlO3_J1CxhWN27Vmoq2FA_HzZE0Jac")
SUPABASE_SERVICE_KEY = os.getenv("SUPABASE_SERVICE_KEY", "")  # Potrzebny do tworzenia tabel

async def setup_knowledge_table():
    """Tworzy tabel knowledge_embeddings w Supabase"""
    
    # SQL do stworzenia tabeli
    create_table_sql = """
    CREATE TABLE IF NOT EXISTS knowledge_embeddings (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        content TEXT NOT NULL,
        metadata JSONB NOT NULL,
        embedding VECTOR(1024),
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
    );
    
    -- Tworzenie indeksu dla wyszukiwania po metadanych
    CREATE INDEX IF NOT EXISTS idx_knowledge_embeddings_metadata_filename 
    ON knowledge_embeddings USING gin ((metadata->'filename'));
    
    -- Tworzenie indeksu dla wyszukiwania wektorowego
    CREATE INDEX IF NOT EXISTS idx_knowledge_embeddings_embedding 
    ON knowledge_embeddings USING ivf_hnsw (embedding vector_cosine_ops);
    
    -- Wlaczenie rozszerzenia vector
    CREATE EXTENSION IF NOT EXISTS vector;
    """
    
    # Najpierw próbujemy z service key
    headers = {
        "Authorization": f"Bearer {SUPABASE_SERVICE_KEY}" if SUPABASE_SERVICE_KEY else f"Bearer {SUPABASE_ANON_KEY}",
        "apikey": SUPABASE_SERVICE_KEY if SUPABASE_SERVICE_KEY else SUPABASE_ANON_KEY,
        "Content-Type": "application/json"
    }
    
    async with httpx.AsyncClient(timeout=30) as client:
        # Utworzenie tabeli przez RPC
        try:
            response = await client.post(
                f"{SUPABASE_URL}/rest/v1/rpc/exec",
                headers=headers,
                json={"query": create_table_sql}
            )
            
            if response.status_code == 200:
                print("Tabela knowledge_embeddings utworzona pomylnie")
                return True
            else:
                print(f"Bd tworzenia tabeli: {response.status_code} - {response.text}")
                
        except Exception as e:
            print(f"Bd wykonania SQL: {e}")
    
    # Fallback - próba przez REST API (moe nie zadziaa bez service key)
    try:
        # Sprawdzenie czy tabela istnieje
        response = await client.get(
            f"{SUPABASE_URL}/rest/v1/knowledge_embeddings?select=id&limit=1",
            headers=headers
        )
        
        if response.status_code == 200:
            print("Tabela knowledge_embeddings ju istnieje")
            return True
        elif response.status_code == 404:
            print("Tabela nie istnieje - potrzebny jest klucz service do jej utworzenia")
            print("Prosz doda SUPABASE_SERVICE_KEY do .env lub utworzy tabel manualnie w Supabase Dashboard")
            return False
        else:
            print(f"Bd sprawdzania tabeli: {response.status_code} - {response.text}")
            return False
            
    except Exception as e:
        print(f"Bd sprawdzania tabeli: {e}")
        return False

async def test_table_access():
    """Testuje dostp do tabeli"""
    
    headers = {
        "Authorization": f"Bearer {SUPABASE_ANON_KEY}",
        "apikey": SUPABASE_ANON_KEY
    }
    
    async with httpx.AsyncClient(timeout=30) as client:
        try:
            response = await client.get(
                f"{SUPABASE_URL}/rest/v1/knowledge_embeddings?select=count&limit=1",
                headers=headers
            )
            
            print(f"Test dostpu - Status: {response.status_code}")
            if response.status_code == 200:
                print("Dostp do tabeli jest poprawny")
                return True
            else:
                print(f"Bd dostpu: {response.text}")
                return False
                
        except Exception as e:
            print(f"Bd testowania dostpu: {e}")
            return False

if __name__ == "__main__":
    asyncio.run(setup_knowledge_table())
    asyncio.run(test_table_access())
