from __future__ import annotations

import re
from collections import Counter


def extract_fallback_keywords(text: str, query: str) -> str:
    raw_combined = (query or "") + " " + (text or "")
    capitalized_words = set(
        re.findall(r"\b[A-ZĄĆĘŁŃÓŚŹŻ][a-pr-uwyząćęłńóśźż]{3,}\b", raw_combined)
    )
    capitalized_lower = {w.lower() for w in capitalized_words}

    allowed_entities = {
        "polska",
        "polski",
        "polsce",
        "ustawa",
        "kodeks",
        "kpc",
        "kpa",
        "saos",
        "eli",
        "urząd",
        "urzedu",
        "skarbowy",
        "skarbowego",
        "trybunał",
        "sejm",
        "senat",
        "minister",
        "prezydent",
        "rząd",
        "wsa",
        "nsa",
        "sn",
        "lubaniu",
        "luban",
        "lubań",
    }

    rejected_names = capitalized_lower - allowed_entities

    stopwords = {
        "oraz",
        "tylko",
        "jego",
        "mnie",
        "który",
        "która",
        "które",
        "przez",
        "jest",
        "będzie",
        "było",
        "być",
        "sobie",
        "tego",
        "jeśli",
        "jeżeli",
        "zatem",
        "więc",
        "także",
        "czyli",
        "jako",
        "taki",
        "taka",
        "takie",
        "może",
        "mogą",
        "musi",
        "muszą",
        "stan",
        "rzecz",
        "dane",
        "inna",
        "inne",
        "zgodnie",
        "artykul",
        "punkt",
        "pisma",
        "sprawy",
        "klienta",
        "zawiera",
        "opis",
        "orzecznictwo",
        "prawo",
        "ustawa",
        "przepisów",
        "wskazuje",
        "podstawie",
        "tekst",
        "analizy",
        "prawnej",
        "dnia",
        "roku",
        "marcin",
        "palka",
        "pałka",
        "kowalski",
        "kowalska",
        "nowak",
        "wiśniewski",
        "wisniewski",
        "wiśniewska",
        "wisniewska",
        "wójcik",
        "wojcik",
        "kowalczyk",
        "kamiński",
        "kaminski",
        "lewandowski",
        "lewandowska",
        "zieliński",
        "zielinski",
        "szymański",
        "szymanski",
        "woźniak",
        "wozniak",
        "dąbrowski",
        "dabrowski",
        "kozłowski",
        "kozlowski",
        "mazur",
        "jankowski",
        "kwiatkowski",
        "kaczmarek",
        "jan",
        "andrzej",
        "piotr",
        "krzysztof",
        "stanisław",
        "stanislaw",
        "tomasz",
        "paweł",
        "pawel",
        "józef",
        "jozef",
        "marek",
        "grzegorz",
        "tadeusz",
        "jerzy",
        "zbigniew",
        "ryszard",
        "dariusz",
        "henryk",
        "mariusz",
        "kazimierz",
        "wiesław",
        "wieslaw",
        "marian",
        "janusz",
        "wojciech",
        "adam",
        "łukasz",
        "lukasz",
        "sebastian",
        "mateusz",
        "damian",
        "przemysław",
        "przemyslaw",
        "radosław",
        "radoslaw",
        "kamil",
        "patryk",
        "mirosław",
        "miroslaw",
        "jacek",
        "arek",
        "arkadiusz",
        "maciej",
        "rafal",
        "rafał",
        "michal",
        "michał",
        "anna",
        "maria",
        "katarzyna",
        "małgorzata",
        "malgorzata",
        "agnieszka",
        "barbara",
        "krystyna",
        "ewa",
        "elżbieta",
        "elzbieta",
        "zofia",
        "janina",
        "teresa",
        "joanna",
        "magdalena",
        "monika",
        "danuta",
        "halina",
        "irena",
        "helena",
        "beata",
        "aleksandra",
        "marta",
        "dorota",
        "marianna",
        "grażyna",
        "grazyna",
        "jolanta",
        "stanisława",
        "stanislawa",
    }

    all_ignored = stopwords.union(rejected_names)

    combined_lower = raw_combined.lower()
    words = re.findall(r"\b[a-pr-uwyząćęłńóśźż]{4,}\b", combined_lower)

    candidates = [w for w in words if w not in all_ignored]
    freq = Counter(candidates)
    common = [item[0] for item in freq.most_common(5)]

    legal_fallbacks = ["wezwanie", "nadpłata", "urząd", "skarbowy", "podatek", "decyzja"]
    for fallback in legal_fallbacks:
        if len(common) >= 5:
            break
        if fallback in combined_lower and fallback not in common and fallback not in all_ignored:
            common.append(fallback)

    if len(common) >= 3:
        return ", ".join(common)

    return "wezwanie, urząd skarbowy, nadpłata, postępowanie"
