-- =============================================================================
-- MIGRACJA: Podział tabeli knowledge_base na dwie oddzielne tabele
-- =============================================================================
-- knowledge_base_legal: Dla dokumentów prawnych (kodeksy, ustawy)
-- knowledge_base_user: Dla dokumentów użytkowników (pisma, skany)
-- =============================================================================

-- 1. Utwórz tabelę knowledge_base_legal z tą samą strukturą
CREATE TABLE knowledge_base_legal (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb,
    embedding vector(1536),
    content_tsv tsvector
);

-- 2. Utwórz tabelę knowledge_base_user z tą samą strukturą
CREATE TABLE knowledge_base_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb,
    embedding vector(1536),
    content_tsv tsvector
);

-- 3. Skopiuj dane z knowledge_base do knowledge_base_legal
-- (zakładamy, że istniejące dane to dane prawne)
INSERT INTO knowledge_base_legal (content, metadata, embedding, content_tsv)
SELECT content, metadata, embedding, content_tsv
FROM knowledge_base
WHERE metadata->>'category' = 'rag_legal' OR metadata->>'category' IS NULL;

-- 4. Skopiuj dane z knowledge_base do knowledge_base_user
-- (dla dokumentów użytkowników)
INSERT INTO knowledge_base_user (content, metadata, embedding, content_tsv)
SELECT content, metadata, embedding, content_tsv
FROM knowledge_base
WHERE metadata->>'category' = 'user_docs';

-- 5. Dodaj indeksy wektorowe dla knowledge_base_legal
CREATE INDEX idx_knowledge_base_legal_embedding
ON knowledge_base_legal USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- 6. Dodaj indeksy wektorowe dla knowledge_base_user
CREATE INDEX idx_knowledge_base_user_embedding
ON knowledge_base_user USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- 7. Dodaj indeksy FTS dla knowledge_base_legal
CREATE INDEX idx_knowledge_base_legal_tsv
ON knowledge_base_legal USING GIN (content_tsv);

-- 8. Dodaj indeksy FTS dla knowledge_base_user
CREATE INDEX idx_knowledge_base_user_tsv
ON knowledge_base_user USING GIN (content_tsv);

-- 9. Funkcja RPC dla knowledge_base_legal
CREATE OR REPLACE FUNCTION match_knowledge_legal(
    query_embedding vector(1536),
    match_threshold float DEFAULT 0.5,
    match_count int DEFAULT 10
)
RETURNS TABLE (
    id bigint,
    content text,
    metadata jsonb,
    similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        kb.id,
        kb.content,
        kb.metadata,
        1 - (kb.embedding <=> query_embedding) AS similarity
    FROM knowledge_base_legal kb
    WHERE 1 - (kb.embedding <=> query_embedding) > match_threshold
    ORDER BY kb.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

-- 10. Funkcja RPC dla knowledge_base_user
CREATE OR REPLACE FUNCTION match_knowledge_user(
    query_embedding vector(1536),
    match_threshold float DEFAULT 0.5,
    match_count int DEFAULT 10
)
RETURNS TABLE (
    id bigint,
    content text,
    metadata jsonb,
    similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        kb.id,
        kb.content,
        kb.metadata,
        1 - (kb.embedding <=> query_embedding) AS similarity
    FROM knowledge_base_user kb
    WHERE 1 - (kb.embedding <=> query_embedding) > match_threshold
    ORDER BY kb.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

-- 11. Funkcje FTS dla knowledge_base_legal
CREATE OR REPLACE FUNCTION search_knowledge_legal_fts(
    search_query text,
    result_limit int DEFAULT 5
)
RETURNS TABLE (
    id bigint,
    content text,
    metadata jsonb,
    rank real
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        kb.id,
        kb.content,
        kb.metadata,
        ts_rank(kb.content_tsv, plainto_tsquery('simple', search_query)) AS rank
    FROM knowledge_base_legal kb
    WHERE kb.content_tsv @@ plainto_tsquery('simple', search_query)
    ORDER BY rank DESC
    LIMIT result_limit;
END;
$$;

-- 12. Funkcje FTS dla knowledge_base_user
CREATE OR REPLACE FUNCTION search_knowledge_user_fts(
    search_query text,
    result_limit int DEFAULT 5
)
RETURNS TABLE (
    id bigint,
    content text,
    metadata jsonb,
    rank real
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        kb.id,
        kb.content,
        kb.metadata,
        ts_rank(kb.content_tsv, plainto_tsquery('simple', search_query)) AS rank
    FROM knowledge_base_user kb
    WHERE kb.content_tsv @@ plainto_tsquery('simple', search_query)
    ORDER BY rank DESC
    LIMIT result_limit;
END;
$$;

-- 13. Trigger dla knowledge_base_legal
CREATE OR REPLACE FUNCTION knowledge_base_legal_tsv_trigger()
RETURNS trigger AS $$
BEGIN
    NEW.content_tsv := to_tsvector('simple', coalesce(NEW.content, ''));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_knowledge_base_legal_tsv ON knowledge_base_legal;
CREATE TRIGGER trg_knowledge_base_legal_tsv
BEFORE INSERT OR UPDATE OF content ON knowledge_base_legal
FOR EACH ROW EXECUTE FUNCTION knowledge_base_legal_tsv_trigger();

-- 14. Trigger dla knowledge_base_user
CREATE OR REPLACE FUNCTION knowledge_base_user_tsv_trigger()
RETURNS trigger AS $$
BEGIN
    NEW.content_tsv := to_tsvector('simple', coalesce(NEW.content, ''));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_knowledge_base_user_tsv ON knowledge_base_user;
CREATE TRIGGER trg_knowledge_base_user_tsv
BEFORE INSERT OR UPDATE OF content ON knowledge_base_user
FOR EACH ROW EXECUTE FUNCTION knowledge_base_user_tsv_trigger();

-- =============================================================================
-- PO MIGRACJI:
-- 1. Zaktualizuj kod aplikacji, aby używał odpowiednich tabel
-- 2. Przeprowadź testy retrieval dla obu tabel
-- 3. Możesz usunąć starą tabelę knowledge_base po weryfikacji
-- =============================================================================